language: java

install:
  gradle assemble

script:
  gradle check

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

after_success:
  - bash <(curl -s https://codecov.io/bash)